#!/bin/bash
#
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.


git diff --cached --name-only --diff-filter=ACM | grep -P '\.ipynb$' |
	while read i;
	do
		# clear all outputs in Jupyter Notebooks
		jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace "$i";
		# re-stage the cleared-out notebooks
		git add "$i";
	done;
